name: Build Local Docker utilizando o Docker Compose

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    # Garante que o comando rode no seu computador (Self-hosted Runner)
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: [14.x] # Angular 12 funciona bem com Node 14
        
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        
      - name: Limpar imagens antigas
        run: docker image prune -f
      #- name: Setup .NET
      #  uses: actions/setup-dotnet@v3
        #with:
           #dotnet-version: '6.0.x'
           
      - name: Remove o container e limpa rede 5000
        continue-on-error: true
        run: docker-compose down --remove-orphans Get-Process -Id (Get-NetTCPConnection -LocalPort 5000).OwningProcess | Stop-Process -Force
        
      #- name: Setup Node.js ${{ matrix.node-version }}
        #uses: actions/setup-node@v3
        #with:
          #node-version: ${{ matrix.node-version }}
          #cache: 'npm'
          
      #- name: Instalar dependências
        #run: npm install

      #- name: Build da aplicação
        #run: npm run build -- --prod
     
      - name: Build Limpo e Deploy
        run: |
          docker-compose build --no-cache
          docker-compose up -d     
       
    #  - name: Build e Up com Docker Compose
        #run: docker-compose up --build -d
          # --build: Força a reconstrução das imagens
          # -d: Roda em segundo plano (detached mode)